global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

alerting:
    alertmanagers:
      - static_configs:
        - targets:
          - prometheus-alertmanager:9093

scrape_configs:
  - job_name: "myapp"
    static_configs:
      - targets: ["myapp:5000"]
  - job_name: "db-exporter"
    static_configs:
      - targets: ["db-exporter:9216"]